name: 'Build FluCoMa Toolkit for Max'
description: 'Builds the FluCoMa Toolkit for Max'
runs:
  using: "composite"
  steps:
    - name: Get Max Source
      run: git clone --recursive https://github.com/Cycling74/max-sdk.git sdk
      shell: bash

    - name: Install (Mac/Linux)
      if: runner.os == 'macOS'
      run: | 
        cmake -GNinja -DMAX_SDK_PATH=../sdk -DFLUID_PATH=../core -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" ..
        ninja install
      working-directory: build
      shell: bash
    
    - name: Install (Windows)
      if: runner.os == 'Windows'
      run: | 
        cmake -DMAX_SDK_PATH="../sdk" -DFLUID_PATH="../core" ..
        cmake --build . --target install --config Release
      working-directory: build
      shell: cmd