name: 'Code signing and notarisation'
description: 'Uses xcode command line tools to sign the binaries and notarise them'
inputs:
  package:
    description: 'Directory containing the release'
    required: true
    default: 'release-packaging'
  glob:
    description: 'Glob for binaries'
    required: true
    default: '-e mxo'
  codesign_options:
    description: 'Whether or not to code sign a hardened runtime'
    default: ''
  output:
    description: 'Output of DMG file'
    default: FluCoMa.dmg
  dmg:
    description: 'Should it sign and notarise as a .dmg'
    default: false
  cert:
    description: 'base64 encoded certificate'
    required: true
  certpwd:
    description: 'Password to unlock the certificate'
    required: true
  teamid:
    description: 'The team identifier for notarisation'
    required: true
  apppwd:
    description: 'One-time password for App Store Conect'
    required: true
  appusr:
    description: 'Username for App Store Connect'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: install fd
      shell: bash
      run: brew install fd

    - name: setup keychain and identities
      shell: bash
      run: |
        # create variables
        CERTPATH=$RUNNER_TEMP/flucoma.p12
        KEYCHAINPWD=foobarbazbob
        KEYCHAINPATH=$RUNNER_TEMP/app-signing.keychain-db

        # We have to do this because the literal block scalar breaks the pipe operator
        echo -n "${{ inputs.cert }}" | base64 --decode --output $CERTPATH
        
        # create temporary keychain
        security create-keychain -p "$KEYCHAINPWD" "$KEYCHAINPATH"

        # append temp keychain to the user domain
        security list-keychain -d user -s "$KEYCHAINPATH"
        security set-keychain-settings "$KEYCHAINPATH"
        security unlock-keychain -p "$KEYCHAINPWD" "$KEYCHAINPATH"

        # import p12 to keychain
        security import "$CERTPATH" -P "${{ inputs.certpwd }}" -A -t cert -f pkcs12 -k "$KEYCHAINPATH" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:, -s -k "$KEYCHAINPATH" -D "${{ inputs.cert }}" -t private "$KEYCHAINPATH"
        
        xcrun notarytool store-credentials "ACPASS" --apple-id ${{ inputs.appusr }} --team-id ${{ inputs.teamid }} --password ${{ inputs.apppwd }}

    - name: DMG Signing
      shell: bash
      if: inputs.dmg
      run: |
        # cd to the package
        cd "${{ inputs.package }}"

        # what are working with here?
        fd ${{ inputs.glob }} -E .git -I

        # sign every binary in the binary directory
        fd ${{ inputs.glob }} -E .git -I -x codesign --options=${{ inputs.codesign_options }} -s "Developer ID Application" {}

        hdiutil create -srcFolder . -o ${{ inputs.output }}
        codesign -s "Developer ID Application" --timestamp -i org.flucoma ${{ inputs.output }}

        xcrun notarytool submit ${{ inputs.output }} --keychain-profile "ACPASS" --wait

    - name: Bundle Signing
      shell: bash
      if: inputs.dmg == false
      run: |
        # cd to the package
        cd "${{ inputs.package }}"

        # create a folder to store the binaries in temporarily once signed
        mkdir -p to_notarise

        # what are working with here?
        fd ${{ inputs.glob }} -E .git -I

        # sign every binary in the binary directory
        fd ${{ inputs.glob }} -E .git -I -x codesign --options=${{ inputs.codesign_options }} -s "Developer ID Application" {}

        # now copy each of those binaries to a folder before notarisation
        fd ${{ inputs.glob }} -E .git -I -x ditto {} to_notarise/{/} 

        # now create a notarisation friendly zip
        /usr/bin/ditto -c -k --keepParent to_notarise to_notarise.zip

        xcrun notarytool submit to_notarise.zip --keychain-profile "ACPASS" --wait

        # rm -rf to_notarise to_notarise.zip

        fd ${{ inputs.glob }} -E .git -I -x xcrun stapler staple {}

