name: 'Build FluCoMa Toolkit for CLI'
description: 'Builds the FluCoMa Toolkit for Command-line Interface'
inputs:
  branch:
    description: 'Which branch to pull flucoma dependencies from (main/dev)'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - name: setup python setup
      uses: actions/setup-python@v2
      id: py39
      with:
        python-version: '3.9'
    - name: check python
      shell: bash
      run: echo "Python is $pythonLocation"        
    - name: Install (Mac/Linux)
      if: runner.os == 'macOS' || runner.os == 'Linux'
      run: | 
        cmake -GNinja -DDOCS=ON -DFLUID_BRANCH=${{ inputs.branch }} -DPython_EXECUTABLE=${{ env.pythonLocation }} ..
        pip install -r _deps/flucoma-docs-src/requirements.txt
        ninja install
      working-directory: build
      shell: bash
    
    - name: Install (Windows)
      if: runner.os == 'Windows'
      run: | 
        cmake -DDOCS=ON -DFLUID_BRANCH=${{ inputs.branch }} -DPython_EXECUTABLE=${{ env.pythonLocation }} ..
        pip install -r _deps/flucoma-docs-src/requirements.txt
        cmake --build . --target install --config Release
      working-directory: build
      shell: cmd
