name: 'Build FluCoMa Toolkit for SuperCollider'
description: 'Builds the FluCoMa Toolkit for SuperCollider'
inputs:
  branch:
    description: 'Which branch to pull flucoma dependencies from (main/production)'
    required: true
    default: 'main'
  build_type:
    description: 'The type of build needed (Debug, Release etc)'
    required: false 
    default: 'Release'
  core_branch: 
    description: 'Select a specific branch for flucoma-core'
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    - name: setup python setup
      uses: actions/setup-python@v3
      id: py39
      with:
        python-version: '3.9'
            
    - name: Get SuperCollider Source
      run: git clone --single-branch --branch main --recursive https://github.com/supercollider/supercollider.git sdk
      shell: bash

    - name: Conditionally download flucoma-core 
      id: core_branch
      if: ${{ inputs.core_branch }} != ${{ inputs.branch }}
      run: |
        git clone --single-branch --branch ${{ inputs.core_branch }} core
        echo "CORE_PATH=-DFETCHCONTENT_SOURCE_DIR_FLUCOMA-CORE=../core" >> "$GITHUB_ENV"
      shell: bash 

    - name: Install (Mac/Linux)
      if: runner.os == 'macOS' || runner.os == 'Linux'
      run: | 
        cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -GNinja -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DSC_PATH=../sdk -DDOCS=ON -DFLUID_BRANCH=${{ inputs.branch }} -DPython_ROOT_DIR=${{ env.pythonLocation }} ${{ steps.core_branch.outputs.CORE_PATH }} ..
        pip install -r _deps/flucoma-docs-src/requirements.txt
        ninja install
      working-directory: build
      shell: bash
    
    - name: Install (Windows)
      if: runner.os == 'Windows'
      run: | 
        cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DSC_PATH="../sdk" -DDOCS=ON -DFLUID_BRANCH=${{ inputs.branch }} -DPython_ROOT_DIR=${{ env.pythonLocation }} ..
        pip install -r _deps/flucoma-docs-src/requirements.txt
        cmake --build . --target install --config Release
      working-directory: build
      shell: cmd
