name: 'Build FluCoMa Toolkit Docs for CLI'
description: 'Builds the FluCoMa Docs Toolkit for CLI'
inputs:
  branch:
    description: 'Which branch to pull dependencies from (main/dev)'
    required: false
    default: 'dev'

runs:
  using: "composite"
  steps:
    - name: install python dependencies
      run: pip3 install -r docs/requirements.txt
      shell: bash
      
    - name: clone latest flucoma-docs
      run: git clone --branch ${{ inputs.branch }} https://github.com/flucoma/flucoma-docs.git docs
      shell: bash

    - name: cmake
      run: cmake -GNinja -DDOCS=ON -DFLUID_DOCS_PATH=../docs -DFLUID_PATH=../core ..
      working-directory: build
      shell: bash

    - name: install
      run: ninja MAKE_CLI_REF
      working-directory: build
      shell: bash