name: 'Get build hash'
description: 'Get the hash of the build from flucoma.version.rc'
outputs:
  version:
    description: "The version SHA of the release"
    value: ${{ steps.retrieve-version.outputs.sha }}

runs:
  using: "composite"
  steps:
    - id: retrieve-version
      run: echo "sha=$(cat flucoma.version.rc)" >> $GITHUB_OUTPUT
      working-directory: core
      shell: bash