name: 'Build FluCoMa Toolkit Docs for Max'
description: 'Builds the FluCoMa Docs Toolkit for Max'
inputs:
  branch:
    description: 'Which branch to pull dependencies from (main/dev)'
    required: false
    default: 'dev'
  target: 
    description: 'Which docs target to build'
    required: false 
    default: 'MAKE_RAW_REF'
    
runs:
  using: "composite"
  steps:
    - name: clone latest flucoma-docs
      run: git clone --single-branch --branch ${{ inputs.branch }} https://github.com/flucoma/flucoma-docs.git docs
      shell: bash

    - name: setup python setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      
    - name: install python dependencies
      run: pip install -r docs/requirements.txt
      shell: bash

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -GNinja -DFLUID_PATH=../core
      working-directory: ${{github.workspace}}/docs
      shell: bash
      
    - name: install
      run: cmake --build ${{github.workspace}}/build --target ${{ inputs.target }}
      shell: bash