name: 'Setup FluCoMa Build Enivronment'
description: 'Installs common tools across FluCoMa continuous integration deployment'
runs:
  using: "composite"
  steps:
    - name: Create build folder
      run: mkdir -p build
      shell: bash

    - name: Clone core repository at HEAD of dev
      run: git clone --branch dev https://github.com/flucoma/flucoma-core.git core
      shell: bash

    # Various Ninja installation steps
    - name: Install ninja (Windows)
      if: ${{ runner.os }} == 'Windows'
      run: choco install ninja
      shell: cmd

    - name: Install ninja (Mac)
      if: ${{ runner.os }} == 'macOS'
      run: brew install ninja
      shell: bash

    - name: Install ninja (Linux)
      if: ${{ runner.os }} == 'Linux'
      run: sudo apt-get install ninja-build
      shell: bash

