name: 'Setup FluCoMa Build Enivronment'
description: 'Installs common tools across FluCoMa continuous integration deployment'
inputs:
  branch:
    description: 'Which branch to pull dependencies from (main/dev)'
    required: false
    default: 'dev'

outputs:
  version:
    description: "The version SHA of the release"
    value: ${{ steps.retrieve-version.outputs.sha }}

runs:
  using: "composite"
  steps:
    - name: Create build folder
      run: mkdir -p build
      shell: bash

    - name: Clone core repository at HEAD of dev
      run: git clone --branch ${{ inputs.branch }} https://github.com/flucoma/flucoma-core.git core
      shell: bash

    - name: retrieve-version
      run: echo "::set-output name=sha::$(cat core/flucoma.version.rc)"
      shell: bash

    - name: Install ninja (Windows)
      if: runner.os == 'Windows'
      run: choco install ninja
      shell: cmd

    - name: Install ninja (Mac)
      if: runner.os == 'macOS'
      run: brew install ninja
      shell: bash

    - name: Install ninja (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install ninja-build
      shell: bash

